### ISSUE TITLE
Not a bug but suggestion

### ISSUE THREAD

**Issue by HavokTracks** [zitreF/CocosMines#2]
First of all love the Mines so great on the SMP

So wondering if there is a possibility to add a "Warning" like last 1 minute the timer turns red?
or a sound played?

That can help players to pay attention.

I might have missed something if that is already possible.

Thanks again for this amazing plug-in

**Comment by zitreF** [comment]
Hello,
thanks for the opinion!

You can use placeholder which was added in the newest version it will return time until next regeneration.
